# Application Configuration
spring.application.name=streamline-be
server.port=8080

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password= # Leave blank since our Docker setup doesn't use one
# spring.data.redis.timeout=60000

# WebSocket Settings
# Allows you to test locally without CORS blocking your HTML file
spring.websocket.cors.allowed-origins=*

# Logging Settings
# Suppresses noisy Spring internal logs so you can easily spot your [Stream] and [PubSub] print statements
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.redis=WARN
logging.level.io.lettuce.core=WARN